export const carousels = [
  { image: "https://i.postimg.cc/4ND4ychv/CXNP9513-1200x300-110322.jpg" },
  {
    image: "https://i.postimg.cc/vHgHGhDH/L1-CXNP9522-1200-X300-12th-MAR22.jpg",
  },
  {
    image:
      "https://i.postimg.cc/5t1xqMg6/m-Brandtiles-Garnier-Men-300-250322.jpg",
  },
  {
    image:
      "https://i.postimg.cc/zfjqxP2p/m-Brandtiles-Parachute-300-250322.jpg",
  },
  { image: "https://i.postimg.cc/8zLp6Ch2/CXNP9519-1200x300-160322.jpg" },
  { image: "https://i.postimg.cc/wjDJhCLr/FMCG-NON-FOOD-BANNER-Feb-v2.jpg" },
];

export const categories = [
  {
    name: "Fruits and Vegetables",
    isActive: true,
    avatarImg:
      "https://i.postimg.cc/R014hCkg/u-https-anmj-org-au-wp-content-uploads-2019-05-Fruit-And-Vegetables-WEB.jpg",
  },
  {
    name: "Food Grains, Oil and Masala",
    isActive: true,
    avatarImg:
      "https://i.postimg.cc/y8nL8mDW/u-https-www-highwayxpress-com-pub-media-catalog-category-food-and-oil.jpg",
  },
  {
    name: "Bakery, Cakes and Dairy",
    isActive: true,
    avatarImg:
      "https://i.postimg.cc/hvD96jB6/u-https-ripe-london-wp-content-uploads-2020-07-dairyproduce.jpg",
  },
  {
    name: "Beverages",
    isActive: true,
    avatarImg:
      "https://i.postimg.cc/hP4r3C4v/Must-Have-Information-On-Soft-Drink-Labels.jpg",
  },
  {
    name: "Snacks and Branded Foods",
    isActive: true,
    avatarImg: "https://i.postimg.cc/sfMSBt2p/category-4-1597824662.jpg",
  },
  {
    name: "Beauty and Hygeine",
    isActive: true,
    avatarImg: "https://i.postimg.cc/X73jMCtp/shutterstock-700270165.jpg",
  },
  {
    name: "Cleaning and Household",
    isActive: true,
    avatarImg: "https://i.postimg.cc/DwXBqSyP/household-cleaning-products.jpg",
  },
  {
    name: "Kitchen Essentials",
    isActive: true,
    avatarImg:
      "https://i.postimg.cc/4406BX0L/10-Kitchen-Essentials-You-Need-To-Have.jpg",
  },
];

//    isActive to show whether item is visible on site
//    isAvailable to show whether item is in stock
export const featuredCategories = [
  {
    homeCatHeader: "Bestsellers in Fruits",
    items: [
      {
        name: "Strawberries",
        variant: "500g",
        sellingPrice: 100,
        discountedSellingPrice: 80,
        discountPercent: 20,
        image:
          "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_bf81a90e-adbb-485e-bfcd-63fb4619a6a7.jpg",
        isActive: true,
        isAvailable: true,
        maxQuantityAllowed: 5,
        cartQuantity: 0,
        slug: "strawberries",
        categorySlug: "fruits-and-vegetables",
        subcategorySlug: "fruits",
      },
      {
        name: "Iceberg Lettuce",
        variant: "250g",
        sellingPrice: 80,
        discountedSellingPrice: 40,
        discountPercent: 50,
        image:
          "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_3ea38082-38f8-41f8-a6fc-0c4ed481c040.jpg",
        isActive: true,
        isAvailable: true,
        maxQuantityAllowed: 5,
        cartQuantity: 2,
        slug: "iceberg-lettuce",
        categorySlug: "fruits-and-vegetables",
        subcategorySlug: "vegetables",
      },
      {
        name: "Red Seedless grapes",
        variant: "300g",
        sellingPrice: 400,
        discountedSellingPrice: 300,
        discountPercent: 25,
        image:
          "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_4f1e62a9-3d61-4f5f-8f71-f51d61cf8cec.jpg",
        isActive: true,
        isAvailable: true,
        maxQuantityAllowed: 5,
        cartQuantity: 0,
        slug: "red-seedless-grapes",
        categorySlug: "fruits-and-vegetables",
        subcategorySlug: "fruits",
      },
      {
        name: "Iceberg Lettuce",
        variant: "250g",
        sellingPrice: 80,
        discountedSellingPrice: 40,
        discountPercent: 50,
        image:
          "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_3ea38082-38f8-41f8-a6fc-0c4ed481c040.jpg",
        isActive: true,
        isAvailable: true,
        maxQuantityAllowed: 5,
        cartQuantity: 1,
        slug: "iceberg-lettuce",
        categorySlug: "fruits-and-vegetables",
        subcategorySlug: "vegetables",
      },
      {
        name: "Red Seedless grapes",
        variant: "300g",
        sellingPrice: 400,
        discountedSellingPrice: 300,
        discountPercent: 25,
        image:
          "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_4f1e62a9-3d61-4f5f-8f71-f51d61cf8cec.jpg",
        isActive: true,
        isAvailable: true,
        maxQuantityAllowed: 5,
        cartQuantity: 0,
        slug: "red-seedless-grapes",
        categorySlug: "fruits-and-vegetables",
        subcategorySlug: "fruits",
      },
      {
        name: "Iceberg Lettuce",
        variant: "250g",
        sellingPrice: 80,
        discountedSellingPrice: 40,
        discountPercent: 50,
        image:
          "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_3ea38082-38f8-41f8-a6fc-0c4ed481c040.jpg",
        isActive: true,
        isAvailable: true,
        maxQuantityAllowed: 5,
        cartQuantity: 4,
        slug: "iceberg-lettuce",
        categorySlug: "fruits-and-vegetables",
        subcategorySlug: "vegetables",
      },
    ],
  },
  {
    homeCatHeader: "Popular in Snacks",
    items: [
      {
        name: "Haldiram Bhujia",
        variant: "1kg",
        sellingPrice: 120,
        discountedSellingPrice: 100,
        discountPercent: 17,
        image: "https://i.postimg.cc/wBHj8ss0/pro-52659.jpg",
        isActive: true,
        isAvailable: true,
        maxQuantityAllowed: 5,
        cartQuantity: 0,
        slug: "strawberries",
        categorySlug: "fruits-and-vegetables",
        subcategorySlug: "fruits",
      },
      {
        name: "Munch",
        variant: "208g",
        sellingPrice: 150,
        discountedSellingPrice: 100,
        discountPercent: 33,
        image: "https://i.postimg.cc/LJjrTMfm/pro-127096.jpg",
        isActive: true,
        isAvailable: true,
        maxQuantityAllowed: 5,
        cartQuantity: 2,
        slug: "iceberg-lettuce",
        categorySlug: "fruits-and-vegetables",
        subcategorySlug: "vegetables",
      },
      {
        name: "Dark Fantasy",
        variant: "300g",
        sellingPrice: 200,
        discountedSellingPrice: 180,
        discountPercent: 10,
        image: "https://i.postimg.cc/JtnCWvwQ/pro-313249.jpg",
        isActive: true,
        isAvailable: true,
        maxQuantityAllowed: 5,
        cartQuantity: 0,
        slug: "red-seedless-grapes",
        categorySlug: "fruits-and-vegetables",
        subcategorySlug: "fruits",
      },
      {
        name: "Nutrichoice Biscuits",
        variant: "200g",
        sellingPrice: 120,
        discountedSellingPrice: 80,
        discountPercent: 34,
        image: "https://i.postimg.cc/Z9xzThKw/pro-392931.jpg",
        isActive: true,
        isAvailable: true,
        maxQuantityAllowed: 5,
        cartQuantity: 1,
        slug: "iceberg-lettuce",
        categorySlug: "fruits-and-vegetables",
        subcategorySlug: "vegetables",
      },
      {
        name: "Act Two Popcorn",
        variant: "450g",
        sellingPrice: 50,
        discountedSellingPrice: 40,
        discountPercent: 20,
        image: "https://i.postimg.cc/Q9YPtNLJ/pro-352110.jpg",
        isActive: true,
        isAvailable: true,
        maxQuantityAllowed: 5,
        cartQuantity: 0,
        slug: "red-seedless-grapes",
        categorySlug: "fruits-and-vegetables",
        subcategorySlug: "fruits",
      },
      {
        name: "Haldiram Bhujia",
        variant: "1kg",
        sellingPrice: 120,
        discountedSellingPrice: 100,
        discountPercent: 17,
        image: "https://i.postimg.cc/wBHj8ss0/pro-52659.jpg",
        isActive: true,
        isAvailable: true,
        maxQuantityAllowed: 5,
        cartQuantity: 0,
        slug: "strawberries",
        categorySlug: "fruits-and-vegetables",
        subcategorySlug: "fruits",
      },
    ],
  },
];
